/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lesson {
  'id' : bigint,
  'title' : string,
  'topic' : string,
  'content' : string,
  'difficulty' : bigint,
}
export interface PracticeProblem {
  'id' : bigint,
  'lessonId' : bigint,
  'topic' : string,
  'question' : string,
  'answer' : string,
}
export interface PracticeProgress {
  'topic' : string,
  'fastestTime' : bigint,
  'attempts' : bigint,
  'correct' : bigint,
}
export interface PracticeSession {
  'topic' : string,
  'duration' : bigint,
  'problemsAttempted' : bigint,
  'timestamp' : bigint,
  'correctCount' : bigint,
}
export interface ProgressView {
  'streak' : bigint,
  'achievements' : Array<string>,
  'completedLessons' : Array<bigint>,
  'practiceScores' : Array<[bigint, bigint]>,
  'practiceSessions' : Array<PracticeSession>,
}
export interface _SERVICE {
  'addAchievement' : ActorMethod<[string], ProgressView>,
  'completeLesson' : ActorMethod<[bigint], ProgressView>,
  'getLessons' : ActorMethod<[], Array<Lesson>>,
  'getLessonsByTopic' : ActorMethod<[string], Array<Lesson>>,
  'getPracticeProblems' : ActorMethod<[], Array<PracticeProblem>>,
  'getPracticeProgressByTopic' : ActorMethod<[string], PracticeProgress>,
  'getPracticeSessions' : ActorMethod<[], Array<PracticeSession>>,
  'getProblemsByTopic' : ActorMethod<[string], Array<PracticeProblem>>,
  'getProgress' : ActorMethod<[], [] | [ProgressView]>,
  'initializeContent' : ActorMethod<[], undefined>,
  'recordPracticeSession' : ActorMethod<[PracticeSession], ProgressView>,
  'submitPracticeScore' : ActorMethod<[bigint, bigint], ProgressView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];