/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PracticeSession = IDL.Record({
  'topic' : IDL.Text,
  'duration' : IDL.Nat,
  'problemsAttempted' : IDL.Nat,
  'timestamp' : IDL.Nat,
  'correctCount' : IDL.Nat,
});
export const ProgressView = IDL.Record({
  'streak' : IDL.Nat,
  'achievements' : IDL.Vec(IDL.Text),
  'completedLessons' : IDL.Vec(IDL.Nat),
  'practiceScores' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'practiceSessions' : IDL.Vec(PracticeSession),
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'difficulty' : IDL.Nat,
});
export const PracticeProblem = IDL.Record({
  'id' : IDL.Nat,
  'lessonId' : IDL.Nat,
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const PracticeProgress = IDL.Record({
  'topic' : IDL.Text,
  'fastestTime' : IDL.Nat,
  'attempts' : IDL.Nat,
  'correct' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAchievement' : IDL.Func([IDL.Text], [ProgressView], []),
  'addMultiplicationProblems' : IDL.Func([], [], []),
  'completeLesson' : IDL.Func([IDL.Nat], [ProgressView], []),
  'getLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getPracticeProblems' : IDL.Func([], [IDL.Vec(PracticeProblem)], ['query']),
  'getPracticeProgressByTopic' : IDL.Func(
      [IDL.Text],
      [PracticeProgress],
      ['query'],
    ),
  'getPracticeSessions' : IDL.Func([], [IDL.Vec(PracticeSession)], ['query']),
  'getProblemsByTopic' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PracticeProblem)],
      ['query'],
    ),
  'getProgress' : IDL.Func([], [IDL.Opt(ProgressView)], ['query']),
  'initializeContent' : IDL.Func([], [], []),
  'recordPracticeSession' : IDL.Func([PracticeSession], [ProgressView], []),
  'submitPracticeScore' : IDL.Func([IDL.Nat, IDL.Nat], [ProgressView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PracticeSession = IDL.Record({
    'topic' : IDL.Text,
    'duration' : IDL.Nat,
    'problemsAttempted' : IDL.Nat,
    'timestamp' : IDL.Nat,
    'correctCount' : IDL.Nat,
  });
  const ProgressView = IDL.Record({
    'streak' : IDL.Nat,
    'achievements' : IDL.Vec(IDL.Text),
    'completedLessons' : IDL.Vec(IDL.Nat),
    'practiceScores' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'practiceSessions' : IDL.Vec(PracticeSession),
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'difficulty' : IDL.Nat,
  });
  const PracticeProblem = IDL.Record({
    'id' : IDL.Nat,
    'lessonId' : IDL.Nat,
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const PracticeProgress = IDL.Record({
    'topic' : IDL.Text,
    'fastestTime' : IDL.Nat,
    'attempts' : IDL.Nat,
    'correct' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAchievement' : IDL.Func([IDL.Text], [ProgressView], []),
    'addMultiplicationProblems' : IDL.Func([], [], []),
    'completeLesson' : IDL.Func([IDL.Nat], [ProgressView], []),
    'getLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getPracticeProblems' : IDL.Func([], [IDL.Vec(PracticeProblem)], ['query']),
    'getPracticeProgressByTopic' : IDL.Func(
        [IDL.Text],
        [PracticeProgress],
        ['query'],
      ),
    'getPracticeSessions' : IDL.Func([], [IDL.Vec(PracticeSession)], ['query']),
    'getProblemsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PracticeProblem)],
        ['query'],
      ),
    'getProgress' : IDL.Func([], [IDL.Opt(ProgressView)], ['query']),
    'initializeContent' : IDL.Func([], [], []),
    'recordPracticeSession' : IDL.Func([PracticeSession], [ProgressView], []),
    'submitPracticeScore' : IDL.Func([IDL.Nat, IDL.Nat], [ProgressView], []),
  });
};

export const init = ({ IDL }) => { return []; };