/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PracticeProblem {
    id: bigint;
    lessonId: bigint;
    topic: string;
    question: string;
    answer: string;
}
export interface ProgressView {
    streak: bigint;
    achievements: Array<string>;
    completedLessons: Array<bigint>;
    practiceScores: Array<[bigint, bigint]>;
    practiceSessions: Array<PracticeSession>;
}
export interface PracticeSession {
    topic: string;
    duration: bigint;
    problemsAttempted: bigint;
    timestamp: bigint;
    correctCount: bigint;
}
export interface Lesson {
    id: bigint;
    title: string;
    topic: string;
    content: string;
    difficulty: bigint;
}
export interface PracticeProgress {
    topic: string;
    fastestTime: bigint;
    attempts: bigint;
    correct: bigint;
}
export interface backendInterface {
    addAchievement(achievement: string): Promise<ProgressView>;
    completeLesson(lessonId: bigint): Promise<ProgressView>;
    getLessons(): Promise<Array<Lesson>>;
    getLessonsByTopic(topic: string): Promise<Array<Lesson>>;
    getPracticeProblems(): Promise<Array<PracticeProblem>>;
    getPracticeProgressByTopic(topic: string): Promise<PracticeProgress>;
    getPracticeSessions(): Promise<Array<PracticeSession>>;
    getProblemsByTopic(topic: string): Promise<Array<PracticeProblem>>;
    getProgress(): Promise<ProgressView | null>;
    initializeContent(): Promise<void>;
    recordPracticeSession(session: PracticeSession): Promise<ProgressView>;
    submitPracticeScore(problemId: bigint, score: bigint): Promise<ProgressView>;
}
import type { ProgressView as _ProgressView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAchievement(arg0: string): Promise<ProgressView> {
        if (this.processError) {
            try {
                const result = await this.actor.addAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAchievement(arg0);
            return result;
        }
    }
    async completeLesson(arg0: bigint): Promise<ProgressView> {
        if (this.processError) {
            try {
                const result = await this.actor.completeLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeLesson(arg0);
            return result;
        }
    }
    async getLessons(): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessons();
            return result;
        }
    }
    async getLessonsByTopic(arg0: string): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonsByTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonsByTopic(arg0);
            return result;
        }
    }
    async getPracticeProblems(): Promise<Array<PracticeProblem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPracticeProblems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPracticeProblems();
            return result;
        }
    }
    async getPracticeProgressByTopic(arg0: string): Promise<PracticeProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getPracticeProgressByTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPracticeProgressByTopic(arg0);
            return result;
        }
    }
    async getPracticeSessions(): Promise<Array<PracticeSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPracticeSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPracticeSessions();
            return result;
        }
    }
    async getProblemsByTopic(arg0: string): Promise<Array<PracticeProblem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProblemsByTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProblemsByTopic(arg0);
            return result;
        }
    }
    async getProgress(): Promise<ProgressView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeContent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeContent();
            return result;
        }
    }
    async recordPracticeSession(arg0: PracticeSession): Promise<ProgressView> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPracticeSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPracticeSession(arg0);
            return result;
        }
    }
    async submitPracticeScore(arg0: bigint, arg1: bigint): Promise<ProgressView> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPracticeScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPracticeScore(arg0, arg1);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProgressView]): ProgressView | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
